language: php

php:
  - 7.3

addons:
  apt:
    packages:
      - libzmq-dev

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dev
  - git clone https://github.com/mkoppanen/php-zmq.git
  - sh -c "cd php-zmq && phpize && ./configure && make --silent && sudo make install"
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/tester -s -p php -c ./tests/php.ini-unix tests

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
